apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
  # important for pods, needed when creating services
    name: postgres-pod
    app: voting-app
spec:
  containers:
  # provide list of containers to be run in the pod
  - name: db
    image: postgres:9.4
    env:
    - name: POSTGRES_PASSWORD
      value: postgres

    - name: POSTGRES_USERNAME
      value: postgres
    ports:
    # expose postgres port in the pod
    - containerPort: 5432