apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
  # important for pods, needed when creating services
    name: redis-pod
    app: voting-app
spec:
  containers:
  # provide list of containers to be run in the pod
  - name: redis
    image: redis
    ports:
    # expose redis port in the pod
    - containerPort: 6379