apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
  # important for pods, needed when creating services
    name: worker-pod
    app: voting-app
spec:
  containers:
  # provide list of containers to be run in the pod
  - name: worker
    image: docker/example-voting-app-result
